/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as FormationsIndexRouteImport } from './routes/formations.index'
import { Route as FormationsSlugRouteImport } from './routes/formations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIndexRoute = FormationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormationsRoute,
} as any)
const FormationsSlugRoute = FormationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FormationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formations': typeof FormationsRouteWithChildren
  '/formations/$slug': typeof FormationsSlugRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formations/$slug': typeof FormationsSlugRoute
  '/formations': typeof FormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formations': typeof FormationsRouteWithChildren
  '/formations/$slug': typeof FormationsSlugRoute
  '/formations/': typeof FormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/formations' | '/formations/$slug' | '/formations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formations/$slug' | '/formations'
  id: '__root__' | '/' | '/formations' | '/formations/$slug' | '/formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormationsRoute: typeof FormationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/': {
      id: '/formations/'
      path: '/'
      fullPath: '/formations/'
      preLoaderRoute: typeof FormationsIndexRouteImport
      parentRoute: typeof FormationsRoute
    }
    '/formations/$slug': {
      id: '/formations/$slug'
      path: '/$slug'
      fullPath: '/formations/$slug'
      preLoaderRoute: typeof FormationsSlugRouteImport
      parentRoute: typeof FormationsRoute
    }
  }
}

interface FormationsRouteChildren {
  FormationsSlugRoute: typeof FormationsSlugRoute
  FormationsIndexRoute: typeof FormationsIndexRoute
}

const FormationsRouteChildren: FormationsRouteChildren = {
  FormationsSlugRoute: FormationsSlugRoute,
  FormationsIndexRoute: FormationsIndexRoute,
}

const FormationsRouteWithChildren = FormationsRoute._addFileChildren(
  FormationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormationsRoute: FormationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
